#!/bin/bash
# This is a script that toggles rotation of the screen through xrandr,
# and also toggles rotation of the stylus, eraser and cursor through xsetwacom

# Check orientation
orientation=`xrandr --verbose -q | grep LVDS1 | awk '{print $5}'`
# Rotate the screen and stylus, eraser and cursor, according to your preferences.
if [ "$orientation" = "normal" ]; then
	/usr/bin/xrandr --output LVDS1 --rotate right
	/usr/bin/xsetwacom set "stylus" Rotate 1
	xsetwacom set "Cursor" Rotate 1
	xsetwacom set "Eraser" Rotate 1
elif [ "$orientation" = "inverted" ]; then
	/usr/bin/xrandr --output LVDS1 --rotate left
	/usr/bin/xsetwacom set "stylus" Rotate 2
	xsetwacom set "Cursor" Rotate 2
	xsetwacom set "Eraser" Rotate 2
elif [ "$orientation" = "right" ]; then
	/usr/bin/xrandr --output LVDS1 --rotate inverted
	/usr/bin/xsetwacom set "stylus" Rotate 3
	xsetwacom set "Cursor" Rotate 3
	xsetwacom set "Eraser" Rotate 3
elif [ "$orientation" = "left" ]; then
	/usr/bin/xrandr --output LVDS1 --rotate normal
	/usr/bin/xsetwacom set "stylus" Rotate 0
	xsetwacom set "Cursor" Rotate 0
	xsetwacom set "Eraser" Rotate 0
fi
